openapi: "3.0.3"
info:
  title: Order Service
  version: "1.0"
servers:
  - url: "https://{hostname}/api"
    variables:
      hostname:
        default: "localhost"
        description: Server hostname

paths:
  /customer/{customerID}/order/{orderID}:
    get:
      description: Get an order
      parameters:
        - in: path
          name: customerID
          schema:
            type: string
          required: true
        - in: path
          name: orderID
          schema:
            type: string
          required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /customer/{customerID}/order/:
    post:
      description: "Create an order"
      parameters:
        - in: path
          name: customerID
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateOrderRequest"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    Order:
      type: object
      properties:
        orderID:
          type: string
        customerID:
          type: string
        status:
          type: string
        items:
          type: array
          items:
            $ref: "#/components/schemas/Item"
        paymentLink:
          type: string
    Item:
      type: object
      properties:
        itemID:
          type: string
        name:
          type: string
        quantity:
          type: integer
          format: int32
        priceID:
          type: string
    Error:
      type: object
      properties:
        msg:
          type: string
    CreateOrderRequest:
      type: object
      required:
        - customerID
        - items
      properties:
        customerID:
          type: string
        items:
          type: array
          items:
            $ref: "#/components/schemas/ItemWithQuantity"
    ItemWithQuantity:
      type: object
      properties:
        itemID:
          type: string
        quantity:
          type: integer
          format: int32
