// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.1
// source: inventorypb/inventory.proto

package inventorypb

import (
	orderpb "github.com/phrara/mallive/common/genproto/orderpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemIDs       []string               `protobuf:"bytes,1,rep,name=itemIDs,proto3" json:"itemIDs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemsRequest) Reset() {
	*x = GetItemsRequest{}
	mi := &file_inventorypb_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemsRequest) ProtoMessage() {}

func (x *GetItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventorypb_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemsRequest.ProtoReflect.Descriptor instead.
func (*GetItemsRequest) Descriptor() ([]byte, []int) {
	return file_inventorypb_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *GetItemsRequest) GetItemIDs() []string {
	if x != nil {
		return x.ItemIDs
	}
	return nil
}

type GetItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*orderpb.Item        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemsResponse) Reset() {
	*x = GetItemsResponse{}
	mi := &file_inventorypb_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemsResponse) ProtoMessage() {}

func (x *GetItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventorypb_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemsResponse.ProtoReflect.Descriptor instead.
func (*GetItemsResponse) Descriptor() ([]byte, []int) {
	return file_inventorypb_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *GetItemsResponse) GetItems() []*orderpb.Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type CheckItemsInventoryRequest struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Items         []*orderpb.ItemWithQuantity `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckItemsInventoryRequest) Reset() {
	*x = CheckItemsInventoryRequest{}
	mi := &file_inventorypb_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckItemsInventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckItemsInventoryRequest) ProtoMessage() {}

func (x *CheckItemsInventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventorypb_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckItemsInventoryRequest.ProtoReflect.Descriptor instead.
func (*CheckItemsInventoryRequest) Descriptor() ([]byte, []int) {
	return file_inventorypb_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *CheckItemsInventoryRequest) GetItems() []*orderpb.ItemWithQuantity {
	if x != nil {
		return x.Items
	}
	return nil
}

type CheckItemsInventoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Items         []*orderpb.Item        `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckItemsInventoryResponse) Reset() {
	*x = CheckItemsInventoryResponse{}
	mi := &file_inventorypb_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckItemsInventoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckItemsInventoryResponse) ProtoMessage() {}

func (x *CheckItemsInventoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventorypb_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckItemsInventoryResponse.ProtoReflect.Descriptor instead.
func (*CheckItemsInventoryResponse) Descriptor() ([]byte, []int) {
	return file_inventorypb_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *CheckItemsInventoryResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *CheckItemsInventoryResponse) GetItems() []*orderpb.Item {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_inventorypb_inventory_proto protoreflect.FileDescriptor

const file_inventorypb_inventory_proto_rawDesc = "" +
	"\n" +
	"\x1binventorypb/inventory.proto\x12\vinventorypb\x1a\x13orderpb/order.proto\"+\n" +
	"\x0fGetItemsRequest\x12\x18\n" +
	"\aitemIDs\x18\x01 \x03(\tR\aitemIDs\"7\n" +
	"\x10GetItemsResponse\x12#\n" +
	"\x05items\x18\x01 \x03(\v2\r.orderpb.ItemR\x05items\"M\n" +
	"\x1aCheckItemsInventoryRequest\x12/\n" +
	"\x05items\x18\x01 \x03(\v2\x19.orderpb.ItemWithQuantityR\x05items\"Z\n" +
	"\x1bCheckItemsInventoryResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result\x12#\n" +
	"\x05items\x18\x02 \x03(\v2\r.orderpb.ItemR\x05items2\xc5\x01\n" +
	"\x10InventoryService\x12G\n" +
	"\bGetItems\x12\x1c.inventorypb.GetItemsRequest\x1a\x1d.inventorypb.GetItemsResponse\x12h\n" +
	"\x13CheckItemsInventory\x12'.inventorypb.CheckItemsInventoryRequest\x1a(.inventorypb.CheckItemsInventoryResponseB7Z5github.com/phrara/mallive/common/genproto/inventorypbb\x06proto3"

var (
	file_inventorypb_inventory_proto_rawDescOnce sync.Once
	file_inventorypb_inventory_proto_rawDescData []byte
)

func file_inventorypb_inventory_proto_rawDescGZIP() []byte {
	file_inventorypb_inventory_proto_rawDescOnce.Do(func() {
		file_inventorypb_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inventorypb_inventory_proto_rawDesc), len(file_inventorypb_inventory_proto_rawDesc)))
	})
	return file_inventorypb_inventory_proto_rawDescData
}

var file_inventorypb_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_inventorypb_inventory_proto_goTypes = []any{
	(*GetItemsRequest)(nil),             // 0: inventorypb.GetItemsRequest
	(*GetItemsResponse)(nil),            // 1: inventorypb.GetItemsResponse
	(*CheckItemsInventoryRequest)(nil),  // 2: inventorypb.CheckItemsInventoryRequest
	(*CheckItemsInventoryResponse)(nil), // 3: inventorypb.CheckItemsInventoryResponse
	(*orderpb.Item)(nil),                // 4: orderpb.Item
	(*orderpb.ItemWithQuantity)(nil),    // 5: orderpb.ItemWithQuantity
}
var file_inventorypb_inventory_proto_depIdxs = []int32{
	4, // 0: inventorypb.GetItemsResponse.items:type_name -> orderpb.Item
	5, // 1: inventorypb.CheckItemsInventoryRequest.items:type_name -> orderpb.ItemWithQuantity
	4, // 2: inventorypb.CheckItemsInventoryResponse.items:type_name -> orderpb.Item
	0, // 3: inventorypb.InventoryService.GetItems:input_type -> inventorypb.GetItemsRequest
	2, // 4: inventorypb.InventoryService.CheckItemsInventory:input_type -> inventorypb.CheckItemsInventoryRequest
	1, // 5: inventorypb.InventoryService.GetItems:output_type -> inventorypb.GetItemsResponse
	3, // 6: inventorypb.InventoryService.CheckItemsInventory:output_type -> inventorypb.CheckItemsInventoryResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_inventorypb_inventory_proto_init() }
func file_inventorypb_inventory_proto_init() {
	if File_inventorypb_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inventorypb_inventory_proto_rawDesc), len(file_inventorypb_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inventorypb_inventory_proto_goTypes,
		DependencyIndexes: file_inventorypb_inventory_proto_depIdxs,
		MessageInfos:      file_inventorypb_inventory_proto_msgTypes,
	}.Build()
	File_inventorypb_inventory_proto = out.File
	file_inventorypb_inventory_proto_goTypes = nil
	file_inventorypb_inventory_proto_depIdxs = nil
}
